global_costmap:
  # ========== 全局坐标系 ==========
  global_frame: map
  robot_base_frame: base_link
  
  # ========== 更新频率 ==========
  update_frequency: 2.0            # 降低更新频率（实时地图计算量大）
  publish_frequency: 1.0
  transform_tolerance: 0.5
  
  # ========== 地图配置 ==========
  rolling_window: false            # 使用静态地图
  static_map: true                 # 使用/map话题
  
  # ========== 分辨率 ==========
  resolution: 0.1                  # 与OctoMap一致
  
  # ========== 插件层 ==========
  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
  
  # ========== 静态层（来自/map） ==========
  static_layer:
    enabled: true
    map_topic: /projected_map      # 订阅OctoMap的2D地图
    subscribe_to_updates: true
    track_unknown_space: true
    use_maximum: false
    lethal_cost_threshold: 100
    unknown_cost_value: 255
    trinary_costmap: true
  
  # ========== 障碍物层（使用/scan） ==========
  obstacle_layer:
    enabled: true
    observation_sources: scan
    scan:
      topic: /scan
      sensor_frame: camera_init
      data_type: LaserScan
      marking: true
      clearing: true
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0
      obstacle_range: 10.0
      raytrace_range: 12.0
    track_unknown_space: true
    combination_method: 1
  
  # ========== 膨胀层 ==========
  inflation_layer:
    enabled: true
    inflation_radius: 0.5          # 机器人半径+安全距离
    cost_scaling_factor: 5.0